### PR TITLE
Persist language selection

### PR DESCRIPTION
**Pull request by garyemerson**
Small change to persist the language selection

### CODE REVIEW

**Comment by garyemerson** [comment]
Ping... are there any concerns with this change? Would love for it to be merged.

**Comment by garyemerson** [comment]
Gonna close for inactivity. Feel free to open this back up if ya wanna.

**Comment by AnmolMago** [comment]
Hey! I need to fix my github notifications, was just notified about a PR being closed that I didn't know exists. Sorry for the very long wait, but I will merge this as it looks good.

Thanks for all your help @garyemerson !

**Comment by AnmolMago** [comment]
It has now been published to the chrome app store as well. Cheers!

**Comment by garyemerson** [comment]
oh cool, good to hear. Thanks!

**Pull request merged**
